services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - jimslab-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  db-dev:
    image: postgres:15-alpine
    networks:
      - jimslab-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    command: postgres -c listen_addresses='*'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prisma-studio:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - .:/app
    command: bunx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - jimslab-network
    depends_on:
      web: 
        condition: service_started

networks:
  jimslab-network:
   name: jimslab-network

volumes:
  postgres_data:
