services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - jimslab-network
    environment:
    - POSTGRES_USER=${DEV_POSTGRES_USER}
    - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
    - POSTGRES_DB=${DEV_POSTGRES_DB}
    - DATABASE_URL=${DEV_DATABASE_URL}
    - AUTH_SECRET=${AUTH_SECRET}
    - AUTH_URL=${DEV_AUTH_URL}
    - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
    - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
    - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED}
    - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  db-dev:
    image: postgres:15-alpine
    networks:
      - jimslab-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
    command: postgres -c listen_addresses='*'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  prisma-studio:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DEV_DATABASE_URL}
    command: bunx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    networks:
      - jimslab-network
    depends_on:
      web: 
        condition: service_started

networks:
  jimslab-network:
   name: jimslab-network

volumes:
  postgres_data:
